garage_compte:
    resource: "@GarageBundle/Controller/CompteController.php"
    type:     annotation

garage:
    resource: "@GarageBundle/Resources/config/routing.yml"
    prefix:   /



Utilisateur:
    resource: "@GarageBundle/Controller/UtilisateurController.php"
    type:     annotation
