# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    

    # firewalls:
    #     # disables authentication for assets and the profiler, adapt it according to your needs
    #     dev:
    #         pattern: ^/(_(profiler|wdt)|css|images|js)/
    #         security: false

    #     main:
    #         anonymous: ~
    #         # activate different ways to authenticate

    #         # http_basic: ~
    #         # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

    #         # form_login: ~
    #         # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    encoders:
            GarageBundle\Entity\Utilisateur:
                algorithm: bcrypt


    providers:
        our_db_provider:
            entity:
                class: GarageBundle:Utilisateur
                property: username

    firewalls:
       secured_area:
            provider: our_db_provider
            anonymous: ~
            logout:
                path:   /logout
                target: /login
            guard:
                authenticators:
                    - form_authenticator


    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_ADMIN }


